CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL UNIQUE,
    last_name  VARCHAR(512)                            NOT NULL UNIQUE,
    email      VARCHAR(255)                            NOT NULL UNIQUE,
    password   VARCHAR(512)                            NOT NULL UNIQUE,
    active     BOOLEAN,
    role       VARCHAR(10)                             NOT NULL
);